default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password123  # Cambiar a tu contraseña real
  host: localhost

development:
  <<: *default
  database: discount_detector_dev

test:
  <<: *default
  database: discount_detector_test